server:
  port: 8089

spring:
  application:
    name: spring-gateway
  zipkin:
    enabled: false
  sleuth:
    reactor:
      instrumentation-type: DECORATE_ON_EACH
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        service-name: ${spring.application.name}
        health-check-critical-timeout: "5m"
        health-check-path: /actuator/health
        health-check-interval: 10s
        hostname: DESKTOP-GJ9JFOE.mshome.net
        catalog-services-watch:
          enabled: false
    gateway:
      metrics:
        enabled: true
        tags:
          path:
            enabled: true
      discovery:
        locator:
          enabled: true
      loadbalancer:
        use404: true

info:
  application:
    name: Spring Cloud Gateway

management:
  health:
    consul:
      enabled: false
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,prometheus
  info:
    env:
      enabled: true

logging:
  level:
    org.springframework.web: TRACE
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: TRACE