server:
  ssl:
    enabled: true
    key-store: classpath:server.jks
    key-store-password: changeit
    key-alias: thinktech

spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          trusted-x509-certificates:
            - classpath:server.crt