spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=Set-Cookie
        - TokenRelay=
        - TokenLoggingFilter=true
      routes:
        - id: spring-consul
          uri: lb://spring-consul
          predicates:
            - Path=/resources/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/training/protocol/openid-connect/certs

