apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-gateway
    skaffold.dev/run-id: 9108a659-39ff-4707-9597-1c2426ae6046
  name: spring-gateway
spec:
  ports:
    - port: 8089
      protocol: TCP
      targetPort: 8089
  selector:
    app: spring-gateway
  type: NodePort
status:
  loadBalancer: {}